### ISSUE TITLE
ttools testsuite occasionally fails

### ISSUE THREAD

**Issue by olebole** [Starlink/starjava#21] opened 2017-12-20 10:41 UTC
We run the testsuites of the Debian starjava packages on any change of the dependencies (which is sometimes more than once a day). In this process, the test suite of ttools [sees in one of ~10 cases](https://ci.debian.net/packages/s/starjava-ttools/unstable/amd64/) a [failure](https://ci.debian.net/data/autopkgtest/unstable/amd64/s/starjava-ttools/20171017_212444/log.gz):

```
    [junit] Testcase: testDOM(uk.ac.starlink.ttools.task.VotCopyTest):	Caused an ERROR
    [junit] Broken pipe
    [junit] org.xml.sax.SAXParseException; systemId: file:/tmp/votcopy6686056133353415594.vot; lineNumber: 191; columnNumber: 10; Broken pipe
    [junit] 	at uk.ac.starlink.votable.SkeletonDOMBuilder$InlineFITSStreamHandler.endElement(SkeletonDOMBuilder.java:521)
    [junit] 	at uk.ac.starlink.votable.CustomDOMBuilder.endElement(CustomDOMBuilder.java:161)
    [junit] 	at uk.ac.starlink.votable.VOTableDOMBuilder.endElement(VOTableDOMBuilder.java:84)
    [junit] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    [junit] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
    [junit] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
    [junit] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
    [junit] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
    [junit] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
    [junit] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
    [junit] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    [junit] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    [junit] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    [junit] 	at uk.ac.starlink.votable.VOElementFactory.parseToDOM(VOElementFactory.java:536)
    [junit] 	at uk.ac.starlink.votable.VOElementFactory.transformToDOM(VOElementFactory.java:391)
    [junit] 	at uk.ac.starlink.votable.VOElementFactory.makeVOElement(VOElementFactory.java:221)
    [junit] 	at uk.ac.starlink.votable.VOElementFactory.makeVOElement(VOElementFactory.java:255)
    [junit] 	at uk.ac.starlink.votable.VOElementFactory.makeVOElement(VOElementFactory.java:267)
    [junit] 	at uk.ac.starlink.ttools.task.VotCopyTest.readDOM(VotCopyTest.java:73)
    [junit] 	at uk.ac.starlink.ttools.task.VotCopyTest.testDOM(VotCopyTest.java:104)
    [junit] Caused by: java.io.IOException: Broken pipe
    [junit] 	at uk.ac.starlink.util.FastPipedOutputStream.write(FastPipedOutputStream.java:167)
    [junit] 	at uk.ac.starlink.util.PipeReaderThread$1.write(PipeReaderThread.java:77)
    [junit] 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    [junit] 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    [junit] 	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
    [junit] 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
    [junit] 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
    [junit] 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
    [junit] 	at uk.ac.starlink.votable.SkeletonDOMBuilder$InlineFITSStreamHandler.endElement(SkeletonDOMBuilder.java:511)
    [junit] 
```

The Debian patches for [ttools](https://sources.debian.org/src/starjava-ttools/3.1.2-1/debian/patches/) and [votable](https://sources.debian.org/src/starjava-votable/2.0+2017.11.07-1/debian/patches/) don't look being a cause for this (maybe except the use of the external `nom.tam.fits` package). However, ttools is still in the version of mid-November (stilts 3.1-2); I didn't had the time to update yet (next week, probably).

**Comment by mbtaylor** [comment] 2017-12-20 11:20
Oh dear that's nasty.  I don't think I've ever seen this in tests or in the running applications, but it must be some kind of race condition.  I don't expect this behaviour would have changed at any time over the last few versions (unless your test history suggests otherwise?).

It has the look of something that might be difficult to diagnose, but I will try to look into it.  Thanks for the report.

**Comment by mbtaylor** [comment] 2019-01-08 15:39
@olebole, sorry it's taken a while.  I have never managed to reproduce this issue, but it seems like your builds are still experiencing it.  I've made a fix on branch pipefix (9e37995) which I think _might_ fix the problem.  Maybe you could try it out for a few weeks and see if it has any effect.

**Comment by mbtaylor** [comment] 2019-03-22 16:25
@olebole, Looking at your tests, that failure doesn't seem to have occurred since January - are you using the fix I suggested?  If so, do you agree that it seems to have made the problem go away?  If you do, then I'll merge it to master and tentatively close this issue.

**Comment by olebole** [comment] 2019-03-22 16:30
Yes, this is applied since January 2019 (applied to the "util" git subtree from 2019-01-04), and it seems that it solved the problem. Sorry that I lost track here and didn't report back.

**Comment by mbtaylor** [comment] 2019-03-22 16:57
Thanks Ole, merged now and will be in the next public release.  Fingers crossed it's sorted, but if it pops up again you can reopen this issue or let me know.

**Closed by mbtaylor** 2019-03-22 16:57 UTC
